services:
  ewm-server:
    container_name: ewm-server
    build: ./main-service
    image: ewm-server
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_db
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345
      - STAT_SERVER_URL=http://stats-server:9090

  ewm-db:
    container_name: ewm-db
    image: postgres:16.1
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ewm_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345

  stats-server:
    container_name: stats-server
    build: ./stat/server
    image: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stat_db
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345

  stats-db:
    container_name: stats-db
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stat_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345